segments:
  - name: "seg_1"
    ground_truth_dir: "input/Seq1/GT"
    cameras:
      - id: "cam0"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_0_seg_1/video_0_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_0.avi"
      - id: "cam1"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_1_seg_1/video_1_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_1.avi"
      - id: "cam2"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_2_seg_1/video_2_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_2.avi"
      - id: "cam3"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_3_seg_1/video_3_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_3.avi"
      - id: "cam4"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_4_seg_1/video_4_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_4.avi"
      - id: "cam5"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_5_seg_1/video_5_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_5.avi"
      - id: "cam6"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_6_seg_1/video_6_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_6.avi"
      - id: "cam7"
        pkl: "input/Seq1/imageSequence/Segments/wham_output_video_7_seg_1/video_7_seg_1.pkl"
        video: "input/Seq1/imageSequence/video_7.avi"
